### ISSUE TITLE
Download link returning 404

### ISSUE THREAD

**Issue by caneleex** [nopbreak/TwitchMod#1]
Download link from the readme is returning 404 after opening. Couldn't you just upload the releases to GitHub?

**Comment by StephanBruh** [comment]
You need to create account. What is impossible to do on the site unless you can read the russian captcha. Download the 4pda app you can register a account without captcha. Or compile it yourself.

I reuploaded it here:
https://stephanbruh.stackstorage.com/s/8V3yVaZp7UxOr3A

**Comment by anonymix007** [comment]
> Download link from the readme is returning 404 after opening. Couldn't you just upload the releases to GitHub?

You have to register if you want to be able to download

**Comment by caneleex** [comment]
> 
> 
> > Download link from the readme is returning 404 after opening. Couldn't you just upload the releases to GitHub?
> 
> You have to register if you want to be able to download

I got that later but the download link is still missing, or it has been deleted. Do you have an apk of the latest update?

**Comment by anonymix007** [comment]
> it has been deleted. 
I think this is the case, in topic someone reported the bug, so it may be the reason. BTW you can still use 8.4.1

**Comment by caneleex** [comment]
Hopefully there will be a new version released in next few days so i'm closing this.
