### ISSUE TITLE
Can't buy bits or subscribe

### ISSUE THREAD

**Issue by sk3ys** [nopbreak/TwitchMod#10]
Hey thanks for working on this twitch mod, everything seems to work fine except whenever I go to subscribe or buy bits it says the application is not configured for billing?

**Comment by Blueberryy** [comment]
Because its a mod? Try to download official app from play market/app store and try again

**Comment by sk3ys** [comment]
Yeah, just thought the mod might be able to as well. The play store version does work with billing.
