### ISSUE TITLE
Channel points auto claim issue

### ISSUE THREAD

**Issue by Fastfinguh** [nopbreak/TwitchMod#18]
My + 50 channel points only get claimed when I (re)open a stream. It doesn't claim them while I'm watching the stream. It worked fine for me a couple releases back (when there was a claim channel point option in the mod settings.)

Edit: Works on b48, doesn't work on b50 and b68

**Comment by nopbreak** [comment]
Can you try latest test build?
https://mega.nz/file/H9xn1TYS#3V4G68tzwU7xk1PCH0Tg-Esu_EPqOBRzvYCB_9pWSik

**Comment by Fastfinguh** [comment]
Been watching for about 30 minutes now and I'm pretty sure I'm capped on the bonus points, since I'm only receiving +10's. I'll post the update as soon as I get any bonuses to claim. I downloaded the b175 from Telegram.
