### ISSUE TITLE
9.8.0 has higher latency to streamer?

### ISSUE THREAD

**Issue by bennyhillthebest** [nopbreak/TwitchMod#23]
I installed the apk on two devices. Today i compared 9.8.0 to 9.1.1 and it looks like that 9.8.0 is behind 3-5 seconds in comparison to 9.1.1. I would speculate that maybe low latency is broken on 9.8.0, hopefully you have the time to look at this issue.

Thank you very very much!
Gino

**Comment by nopbreak** [comment]
Hi. Try clear app data or uninstall old version first.

**Comment by bennyhillthebest** [comment]
You're right. Clean installing fixed. Thank you forthe swift suggestion!!!
