### ISSUE TITLE
Why do we need to create accounts on 3rd party sites to install this?

### ISSUE THREAD

**Issue by brian6932** [nopbreak/TwitchMod#25]
Does anyone have a direct link for the newest version?

**Comment by anonymix007** [comment]
https://yadi.sk/d/t89YHd3zrjsdTw

**Comment by brian6932** [comment]
I ended up making an account, but @nopbreak should post his releases on a the releases page, that way we can track releases and get notified on new updates

**Comment by anonymix007** [comment]
Shouldn't it lead to legal issues (e.g. deleting repo because of dmca)?

**Comment by brian6932** [comment]
It could, I don't know how strict github is with this nowadays. While slightly different in circumstances, TTV ad-block is hosted on github
https://github.com/odensc/ttv-ublock

**Comment by nopbreak** [comment]
Fixed
