### ISSUE TITLE
Add an option to adjust the seek time

### ISSUE THREAD

**Issue by asdsadsaasd12312132** [nopbreak/TwitchMod#28]
Seek refers to the buttons to skip back or forward. This is currently locked at 30 seconds. I find this amount to be absurdly high. When I want to rewatch something, I usually only need to skip back 5-10 seconds. Skipping back 30 seconds basically forces me to waste 20 seconds to return to the part I want to rewatch. I could manually navigate the seek bar but this is difficult on a phone. I suggest adding options to change the seek amount to something like 5, 10, 15, 30, and 60 seconds.

**Comment by nopbreak** [comment]
added in 2.7. Test build: https://www.solidfiles.com/v/X8dzV5K6xrX8M
