### ISSUE TITLE
the hype locomotive will remain at 0:01 and will not hide

### ISSUE THREAD

**Issue by OvGamesYT** [nopbreak/TwitchMod#31]
the hype locomotive will remain at 0:01 and will not hide ![Screenshot_2020-11-29-02-18-43-68_f56d448df78e8512261d4bfbcb3978c7.jpg](https://user-images.githubusercontent.com/56827421/100525251-4635bd00-31e9-11eb-969f-e3cc9f25f7f8.jpg)

**Comment by nopbreak** [comment]
Fixed in 2.8
