### ISSUE TITLE
Whispers and bttv not working properly

### ISSUE THREAD

**Issue by kw0n** [nopbreak/TwitchMod#4]
Hey nop,

Whisper are not working properly on the latest build 809010r3 and a few previous builds. I can open the whisper menu on a pixel XL and Nexus 9 but it will not let me send a message on either device. Other people can send messages to me and I can respond to them but I cannot start the message first.

Bttv emote menu does not show up on pixel XL but does show up on Nexus 9. Bttv emotes do show up in chat display for both devices.

**Comment by kw0n** [comment]
Apologies for the whisper issue, it was my adblocking setup causing the issue. But the other issue with bttv menu not showing up on Android 10 on pixel XL is still persistent

**Comment by nopbreak** [comment]
Hi. Check this build: https://www.solidfiles.com/v/nDKByBRvnPxzP
Android 10 (Emulator): https://imgur.com/a/FGucAEn

**Comment by kw0n** [comment]
I'm on the latest unstable build 9.0.0 BETA but it still is having an issue displaying bttv menu emotes on Android 10 pixel XL. It shows them perfectly on the Nexus 9 tablet though running Android 8.1

**Comment by nopbreak** [comment]
Fixed
