### ISSUE TITLE
Когда поддержка опросов?

### ISSUE THREAD

**Issue by Blueberryy** [nopbreak/TwitchMod#6]
В последней версии приложения Twitch поддерживаются опросы. Когда его и сюда добавят?

**Comment by nopbreak** [comment]
В новой сборке есть поддержка опросов (Twitch 9.0.0 BETA): https://www.solidfiles.com/v/nDKByBRvnPxzP

**Comment by Blueberryy** [comment]
Ссылка не работает. Или файл битый?

**Comment by nopbreak** [comment]
YandexDisk: https://yadi.sk/d/KshgQnOg8tsvrA

**Comment by Blueberryy** [comment]
Спасибо.
