### ISSUE TITLE
Emote menu only shows Twitch/subscribed channel emotes, no BTTV

### ISSUE THREAD

**Issue by Cipheriax** [nopbreak/TwitchMod#7]
![Screenshot_20200502-124832_Twitch](https://user-images.githubusercontent.com/56313064/80862187-3ebe2d80-8c73-11ea-9d18-b11e2522a1f7.jpg)

setting is enabled, all I can see are the usual Twitch emotes as well as those from my subscribed channel.
Clearing cache or data, reinstalling the app and trying out different builds doesn't help as well.

Android 10, Samsung Galaxy Tab S6 LTE (SM-T865)

**Comment by nopbreak** [comment]
Hello, @Cipheriax.  Can you provide logcat output?

**Comment by Cipheriax** [comment]
hey there!
sure! https://pastebin.com/SafSqQsZ

I hope this helps, I've never used logcat or anything like this before. If you need a specific thing to be logged, just tell me and I'll try to realize that!
I was using Logcat Reader available on Play Store.

**Comment by Cipheriax** [comment]
@nopbreak (tagging cause you tagged me as well and I'm not sure whether you notice my comment if I don't tag)

**Comment by nopbreak** [comment]
Try this build: https://www.solidfiles.com/v/j6nervrDW8M8V

**Comment by Cipheriax** [comment]
@nopbreak alright! Tried both (v1 & v2), on the first I also recorded my screen so you can follow what exactly I'm doing to try to make it work. logcat v1: https://drive.google.com/open?id=1QYwTvUvnafgxLODTeCxIse96Yunzs_jU

recording (v1): https://drive.google.com/open?id=1Y49vAtypNOSY73WMZRKxbDFD1dk7-z1F

logcat v2: https://drive.google.com/open?id=173DWAL-65j7WFUJ0BrWbQ97KY9K5-USZ

emote menu doesn't show up on neither both, on the app's start I also tried to disable and enable the menu again as you can see on the recording.

I hope this can help trying to figure out what's the issue here. Thank you very much for your time you put into this (:

**Comment by nopbreak** [comment]
All logs looks ok. I change injection method and add more debug info: https://www.solidfiles.com/v/j6njqN3aKza2Q

**Comment by Cipheriax** [comment]
@nopbreak still nothing https://drive.google.com/open?id=1uDR3TLNPCxy-FQeUje16IvCOoSgv00lh

am I doing anything wrong? It's weird that it's apparently only me is having this issue

**Comment by nopbreak** [comment]
This is reproducing only on Android 10 ARM (#4). Other versions (including emulator) looks good.

**Comment by Cipheriax** [comment]
> This is reproducing only on Android 10 ARM (#4). Other versions (including emulator) looks good.

well, I have the same problem on my phone which is on Android 9 (well, now it's on Android 10 Beta, but when I tried it yesterday, it was on Pie and it didn't work either)
though since now I'm on 10 on my phone as well, I tried this one https://github.com/nopbreak/TwitchMod/issues/7#issuecomment-623115847 out and it also doesn't show up.

**Comment by ubergeek77** [comment]
In case it helps, I can also reproduce this issue on Android 10 on a Pixel 3 XL. FFZ and BTTV emotes don't show up in the menu.

***But,*** they *do* show up if I type a : colon and start typing a BTTV/FFZ emote.

For example, if I type :monka into chat, I can see suggestions for non-Twitch emotes that start with monka (monkaS, monkaTOS, monkaHmm, etc). This isn't a problem for me because I usually know what emotes I want to type starts with (I actually didn't know they were supposed to show up in the menu).

So they *do* show up in the quick menu with a :colon, but they don't show up in the menu with the rest of the emotes.

**Comment by nopbreak** [comment]
I tried on different emulators (Android Emulator and Genymotion) and unfortunately I'm still unable to reproduce this bug.
Test build: https://www.solidfiles.com/v/gNVvY8M7P4Axy

**Comment by Cipheriax** [comment]
> In case it helps, I can also reproduce this issue on Android 10 on a Pixel 3 XL. FFZ and BTTV emotes don't show up in the menu.
> 
> _**But,**_ they _do_ show up if I type a : colon and start typing a BTTV/FFZ emote.
> 
> For example, if I type :monka into chat, I can see suggestions for non-Twitch emotes that start with monka (monkaS, monkaTOS, monkaHmm, etc). This isn't a problem for me because I usually know what emotes I want to type starts with (I actually didn't know they were supposed to show up in the menu).
> 
> So they _do_ show up in the quick menu with a :colon, but they don't show up in the menu with the rest of the emotes.

the thing you mentioned doesn't have to do anything with the actual emote menu, suggestions when I type ":monka" still show up, even when I disabled the emote menu option.

@nopbreak tried the new build, still doesn't work ¯\_(ツ)_/¯ 
I actually didn't know about the suggestion feature though, that's better than nothing (typing emotes with proper capitalization is a pain in landscape mode, so typing only the beginning instead of the full emote definitely helps a lot. The menu would still be nice tho :D)

**Comment by sk3ys** [comment]
Just thought i'd update. I can confirm the emote menus are now working on my galaxy S9 running Android 10

**Comment by nopbreak** [comment]
Fixed
